# Add target: 
# fly -t <target> login -c http://192.168.100.4:8080/

resources:

- name: Download Source
  type: git
  source:
    uri: https://github.com/Haynesy/RayTracerHaskell.git

jobs:

- name: Run Application
  public: true
  plan: 
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: "14.04"}
      run:
        get: Download Source
        path: ls
        args: [-a]
    #file: ./ops/Run.yml
 
 
# Add the pipeline
# fly -t <target> set-pipeline -p <pipeline> -c <filename>

# Update pipeline
# fly -t <target> -p <pipeline> -c <filename>

